/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/koyLyzGgq44
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function Dashboard() {

  const currentTime = new Date().toLocaleTimeString();
  return (
    (
    <>
          <header className="bg-gray-900 text-white py-4 px-6 shadow-md">
        <div className="container mx-auto flex justify-between items-center">
          <h1 className="text-2xl font-bold">TiHAN Traffic Flow</h1>
          <nav className="hidden md:block">
            <ul className="flex space-x-4  ">
              <li>
                <a href="#" className="hover:text-gray-300">
                  Home
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-gray-300">
                  Analytics
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-gray-300">
                  Settings
                </a>
              </li>
              <li>
                <a href="#" className="hover:text-gray-300">
                  Help
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </header>
    <div className="grid md:grid-cols-[300px_1fr] gap-6 p-4 md:p-6">
      <div className="bg-white rounded-lg shadow-lg p-6 space-y-4 border-black border-2 dark:bg-gray-950">
        <h2 className="text-xl font-bold">Input Parameters</h2>
        <form className="space-y-4">
        <div className="space-y-2">
            <Label className="text-left" htmlFor="status">Station</Label>
            <Select id="status">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select a station" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="active">Station 1</SelectItem>
                  <SelectItem value="inactive">Station 2</SelectItem>
                  <SelectItem value="pending">Station 3</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="status">Model</Label>
            <Select id="status">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select a model" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="active">Model 1</SelectItem>
                  <SelectItem value="inactive">Model 2</SelectItem>
                  <SelectItem value="pending">Model 3</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-2">
            <Label htmlFor="name">Current Count</Label>
            <Input id="name" type='number' placeholder="Enter Current Count" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="email">Count Prediction</Label>
            <Input id="email" type='number' placeholder="Count prediction for next 5 mins"  />
          </div>
          {/* <div className="space-y-2">
            <Label htmlFor="status">Status</Label>
            <Select id="status">
              <SelectTrigger className="w-full">
                <SelectValue placeholder="Select a status" />
              </SelectTrigger>
              <SelectContent>
                <SelectGroup>
                  <SelectItem value="active">Active</SelectItem>
                  <SelectItem value="inactive">Inactive</SelectItem>
                  <SelectItem value="pending">Pending</SelectItem>
                </SelectGroup>
              </SelectContent>
            </Select>
          </div> */}
          <Button className="w-full" type="submit">
            Get Predictions
          </Button>
        </form>
      </div>
      <div className="bg-white rounded-lg shadow-lg p-6 border-black border-2 dark:bg-gray-950">
        <div className="mb-4">
          <h2 className="text-2xl font-bold">Count Readings</h2>
          <p className="text-gray-500 dark:text-gray-400">A list of all count predictions in the system.</p>
        </div>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Time</TableHead>
              <TableHead>Current Count</TableHead>
              <TableHead>Status</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell>{currentTime}</TableCell>
              <TableCell>45</TableCell>
              <TableCell>Active</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>{currentTime}</TableCell>
              <TableCell>56</TableCell>
              <TableCell>Inactive</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>{currentTime}</TableCell>
              <TableCell>4</TableCell>
              <TableCell>Pending</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>{currentTime}</TableCell>
              <TableCell>22</TableCell>
              <TableCell>Active</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>{currentTime}</TableCell>
              <TableCell>13</TableCell>
              <TableCell>Inactive</TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    </div>
    </>)
  );
}
